//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public Customers()
        {
            this.Receipts = new HashSet<Receipts>();
        }
    
        public int CustomerID { get; set; }
        public string Phone { get; set; }
        public string FullName { get; set; }
        public string BonusCardNumber { get; set; }
        public decimal BonusBalance { get; set; }
        public bool IsActive { get; set; }
        public string INN { get; set; }
    
        public virtual ICollection<Receipts> Receipts { get; set; }
    }
}
