//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employees
    {
        public Employees()
        {
            this.Receipts = new HashSet<Receipts>();
            this.Shifts = new HashSet<Shifts>();
        }
    
        public int EmployeeID { get; set; }
        public int RoleID { get; set; }
        public string FullName { get; set; }
        public string INN { get; set; }
        public string PinCode { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual ICollection<Receipts> Receipts { get; set; }
        public virtual ICollection<Shifts> Shifts { get; set; }
    }
}
