//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public Products()
        {
            this.Receipt_Items = new HashSet<Receipt_Items>();
        }
    
        public int ProductID { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string Article { get; set; }
        public string Barcode { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public int MeasureUnitID { get; set; }
        public int VATRateID { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public Nullable<int> StockQuantity { get; set; }
    
        public virtual MeasureUnits MeasureUnits { get; set; }
        public virtual Product_Groups Product_Groups { get; set; }
        public virtual Tax_Rates Tax_Rates { get; set; }
        public virtual ICollection<Receipt_Items> Receipt_Items { get; set; }
    }
}
