//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Groups
    {
        public Product_Groups()
        {
            this.Products = new HashSet<Products>();
        }
    
        public int GroupID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Products> Products { get; set; }
    }
}
