//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipt_Items
    {
        public int ItemID { get; set; }
        public int ReceiptID { get; set; }
        public int ProductID { get; set; }
        public decimal Quantity { get; set; }
        public decimal Price { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
    
        public virtual Products Products { get; set; }
        public virtual Receipts Receipts { get; set; }
    }
}
