//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receipts
    {
        public Receipts()
        {
            this.Receipt_Items = new HashSet<Receipt_Items>();
        }
    
        public int ReceiptID { get; set; }
        public int ShiftID { get; set; }
        public int EmployeeID { get; set; }
        public int TaxSystemID { get; set; }
        public bool IsReturn { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public int PaymentTypeID { get; set; }
        public decimal ReceiptDiscount { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public int StatusID { get; set; }
    
        public virtual Customers Customers { get; set; }
        public virtual Employees Employees { get; set; }
        public virtual Payment_Types Payment_Types { get; set; }
        public virtual ICollection<Receipt_Items> Receipt_Items { get; set; }
        public virtual Shifts Shifts { get; set; }
        public virtual Statuses Statuses { get; set; }
        public virtual Tax_Systems Tax_Systems { get; set; }
    }
}
