//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shifts
    {
        public Shifts()
        {
            this.Receipts = new HashSet<Receipts>();
        }
    
        public int ShiftID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime OpenedAt { get; set; }
        public Nullable<System.DateTime> ClosedAt { get; set; }
    
        public virtual Employees Employees { get; set; }
        public virtual ICollection<Receipts> Receipts { get; set; }
    }
}
