//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax_Systems
    {
        public Tax_Systems()
        {
            this.Receipts = new HashSet<Receipts>();
        }
    
        public int TaxSystemID { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<Receipts> Receipts { get; set; }
    }
}
