//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoCash.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Receipt_Totals
    {
        public int ReceiptID { get; set; }
        public decimal SubTotalAmount { get; set; }
        public decimal ReceiptDiscount { get; set; }
        public Nullable<decimal> TotalAmountToPay { get; set; }
    }
}
